### ISSUE TITLE
Linting in the CI process

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#51]
We already run tests, but are not running a linter. @pmoura 's logtalk seems to have a great linter that we could use.

**Comment by pmoura** [comment]
Indeed most of the feedback I have been providing, both as issues and pull requests, result from applying the Logtalk tools to the Prolog files in this project (I routinely perform these checks on several public Prolog projects as part of the development of Logtalk tools). In a few cases, feedback result from manual code inspections.

Is possible with some effort to automate running the Logtalk linter. Not all files can be fully checked, however, due to compilation errors that result from trying to compile modules as objects as required to use the linter. These errors result from the use of proprietary stuff inside modules that cannot be sensibly supported (Logtalk is Prolog system agnostic). Still, the number of reported issues have been helpful in improving several projects.

Currently, in the `dev` branch, most reported lint issues are missing `use_module/1-2` and `multifile/1` directives. There are several module dependencies in several modules that are undeclared with the code only working due to the auto-loading mechanism. While I think this is bad practice, it's also widespread practice (among SWI-Prolog users) and thus I hesitate in submitting a pull request that adds all those missing directives. Your call. Note, however, that the linter is controlled by a set of flags and thus is simple to turn off these particular warnings.

I can look into the best way of automating running the linter if you want and report back. I will need to run some tests on my Ubuntu VM, however, as my main OS is macOS and the required packs by your project cannot currently all be installed on macOS.

**Comment by pmoura** [comment]
Yesterday and this morning I moved from the linter to the checking targets provided by Logtalk's make tool (https://logtalk.org/manuals/refman/predicates/logtalk_make_1.html), which resulted in some new issues and pull requests. So, ideally, CI would run both.

**Comment by matko** [comment]
@rrooij is this still something you want to look into?

**Comment by matko** [comment]
We've been linting prolog code for quite a while now, mainly to ensure that all imports are present. If we need more linting than that, open a separate issue.
